Adding POLY2 table for GF180 DRC
efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv pull request #42
Opened 2023-02-08 13:51 UTC by FaragElsayed2

## Adding POLY2 table for GF180 DRC

2023-02-08 13:53 UTC, FaragElsayed2 commented
@atorkmabrains Ready to review

2023-02-08 14:23 UTC, atorkmabrains requested changes
@FaragElsayed2 Please check

2023-02-08 14:23 UTC, atorkmabrains commented on klayout/drc/rule_decks/poly2.drc
> +  # rule PL.10 is not a DRC check
@FaragElsayed2 Please add link.

2023-02-08 14:35 UTC, FaragElsayed2 commented on klayout/drc/rule_decks/poly2.drc
> +  # rule PL.10 is not a DRC check
Done @atorkmabrains

2023-02-09 13:03 UTC, atorkmabrains approved these changes

2023-02-09 13:03 UTC, merged