Adding LVS environment for GF180MCU
efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv pull request #74
Opened 2023-02-14 08:23 UTC by FaragElsayed2

## Adding LVS environment for GF180MCU

2023-02-14 14:54 UTC, atorkmabrains requested changes

2023-02-14 14:54 UTC, atorkmabrains commented on klayout/lvs/README.md
> +📦runset
@FaragElsayed2 Please change the icon to folder as requested by proppy.

2023-02-14 14:54 UTC, atorkmabrains commented on klayout/lvs/README.md
> +# LVS Documentation
@FaragElsayed2 Please update the LVS documentation.

2023-02-14 14:56 UTC, FaragElsayed2 commented on klayout/lvs/testing/Makefile
> +#==========================
`Help section` To be removed

2023-02-14 15:07 UTC, atorkmabrains commented
@FaragElsayed2 Remove fab/man test cases and use a single folder for unit testing and avoid complexity.

2023-02-14 15:08 UTC, atorkmabrains commented
@FaragElsayed2 split the lvs file into sections and include each in the main LVS file.

2023-02-14 15:21 UTC, atorkmabrains commented
Inside the test cases, we need the following folder structure:
```
--testcases
|---->unit
|       |----> group
|                 |-----> layout
|                 |-----> netlist
|.....
```

2023-02-15 14:55 UTC, FaragElsayed2 commented on klayout/lvs/README.md
> +📦runset
Done

2023-02-15 14:55 UTC, FaragElsayed2 commented on klayout/lvs/README.md
> +# LVS Documentation
Done

2023-02-15 14:55 UTC, FaragElsayed2 commented on klayout/lvs/testing/Makefile
> +#==========================
Done

2023-02-15 14:57 UTC, FaragElsayed2 commented
@atorkmabrains 

- LVS runset has been spliited into sections as agreed 
- New folder structure is added and testcases have been fixed
- Regression is changed and could be run multi-threaded now with more detailed results.


Still need to add switches for devices that need it to pass CI

2023-03-22 10:53 UTC, closed without merging